--DBS211 Group 7
--MS3-Database Scripting and Creation
--Group Members:Ruolin Wu, Tsz Wa Wong, Yong Li
--MS3: Table Creation
--Create the table of pet clinic:
DROP TABLE CLINIC;
CREATE TABLE CLINIC(
CLINICID INT PRIMARY KEY,
CLINICNAME VARCHAR(30) NOT NULL,
CLINICADDRESS VARCHAR(50) NOT NULL,
CLINICEMAIL VARCHAR(50) NOT NULL,
CLINICPHONENUMBER INT NOT NULL,
CONSTRAINT 
CLINIC_ID_CHK CHECK(CLINICID BETWEEN 1 AND 99999),
CONSTRAINT
PHONE_CHK CHECK(CLINICPHONENUMBER BETWEEN 10000000000 AND 19999999999)
);
--Create the table of vets information:
DROP TABLE VETERINARIANS;
CREATE TABLE VETERINARIANS(
VETID INT PRIMARY KEY,
CLINICID INT ,
VETFIRSTNAME VARCHAR(25) NOT NULL,
VETLASTNAME VARCHAR(25) NOT NULL,
VETEMAIL VARCHAR(30) NOT NULL,
VETPHONENUM INT NOT NULL,
CONSTRAINT 
CLINICID_FK FOREIGN KEY(CLINICID) REFERENCES CLINIC(CLINICID),
CONSTRAINT
VETID_CHK CHECK(VETID BETWEEN 1 AND 99999),
CONSTRAINT
VETPHONENUME_CHK CHECK(VETPHONENUM BETWEEN 10000000000 AND 19999999999)
);

--Create the table of services:
DROP TABLE SERVICES;
CREATE TABLE SERVICES(
SERVICENAME VARCHAR(30) PRIMARY KEY,
PRICE DECIMAL(5,2) NOT NULL,
SERVICEDES VARCHAR(100) NOT NULL,
CONSTRAINT
PRICE_CHK CHECK(PRICE BETWEEN 1 AND 999999)
);
--Create the table of pet owners:
DROP TABLE OWNERS;
CREATE TABLE OWNERS(
OWNERID INT PRIMARY KEY,
OWNERFIRSTNAME VARCHAR(25) NOT NULL,
OWNERLASTNAME VARCHAR(25) NOT NULL,
OWNEREMAIL VARCHAR(30) NOT NULL,
OWNERADDRESS VARCHAR(100),
OWNERPOSTALCODE VARCHAR(6),
OWNERPHONENUM INT NOT NULL,
CONSTRAINT
OWNERID_CHK CHECK(OWNERID BETWEEN 1 AND 99999),
CONSTRAINT
OWNERPHONENUM_CHK CHECK(OWNERPHONENUM BETWEEN 10000000000 AND 19999999999)
);

--Create the table of pet information:
DROP TABLE PETS;
CREATE TABLE PETS(
PETID INT PRIMARY KEY,
OWNERID INT,
PETSNAME VARCHAR(25) NOT NULL,
BREEDS VARCHAR(25) NOT NULL,
AGE INT NOT NULL,
ISNEUTERED VARCHAR(5) NOT NULL,
PETTYPE VARCHAR(25) NOT NULL,
CONSTRAINT 
OWNERID_FK FOREIGN KEY(OWNERID) REFERENCES OWNERS(OWNERID),
CONSTRAINT
PETID_CHK CHECK(PETID BETWEEN 1 AND 99999)
);
--Create the table of appointments:
DROP TABLE APPOINTMENTS;
CREATE TABLE APPOINTMENTS(
APPOINTID INT PRIMARY KEY,
PETID INT NOT NULL,
SERVICENAME VARCHAR(30) NOT NULL,
VETID INT NOT NULL,
APPOINTMENTDATE DATE NOT NULL,
APPOINTMENTTIME VARCHAR(10) NOT NULL,
REASONFORVISIT VARCHAR(1000) NOT NULL,
CONSTRAINT
PETID_FKS FOREIGN KEY(PETID) REFERENCES PETS(PETID),
CONSTRAINT
SERVICESNAME_FKS FOREIGN KEY(SERVICENAME) REFERENCES SERVICES(SERVICENAME),
CONSTRAINT
VETID_FKS FOREIGN KEY(VETID) REFERENCES VETERINARIANS(VETID),
CONSTRAINT
APPOINTID_CHK CHECK(APPOINTID BETWEEN 1 AND 99999)
);

COMMIT;
